samples['SingleEle-Run2016B-PromptReco-v2']   = ['/SingleElectron/Run2016B-PromptReco-v2/MINIAOD',[]]
samples['SingleEle-Run2016C-PromptReco-v2']   = ['/SingleElectron/Run2016C-PromptReco-v2/MINIAOD',[]]
samples['SingleEle-Run2016D-PromptReco-v2']   = ['/SingleElectron/Run2016D-PromptReco-v2/MINIAOD',[]]
samples['SingleEle-Run2016E-PromptReco-v2']   = ['/SingleElectron/Run2016E-PromptReco-v2/MINIAOD',[]]
samples['SingleEle-Run2016F-PromptReco-v1']   = ['/SingleElectron/Run2016F-PromptReco-v1/MINIAOD',[]]
samples['SingleEle-Run2016G-PromptReco-v1']   = ['/SingleElectron/Run2016G-PromptReco-v1/MINIAOD',[]]
