root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"zee\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"zmm\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"gam\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"wen\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"wmn\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"topmu\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"Recoil[GeV]\",\"topel\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",1,\"met\",\"E_{T}^{miss}[GeV]\",\"SR\",false,true\)
