#samples['SingleMu-Run2016B-PromptReco-v2']   = ['/SingleMuon/Run2016B-PromptReco-v2/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]
#samples['SingleMu-Run2016C-PromptReco-v2']   = ['/SingleMuon/Run2016C-PromptReco-v2/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]
#samples['SingleMu-Run2016D-PromptReco-v2']   = ['/SingleMuon/Run2016D-PromptReco-v2/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]
#samples['SingleMu-Run2016E-PromptReco-v2']   = ['/SingleMuon/Run2016E-PromptReco-v2/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]
#samples['SingleMu-Run2016F-PromptReco-v1']   = ['/SingleMuon/Run2016F-PromptReco-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]
#samples['SingleMu-Run2016G-PromptReco-v1']   = ['/SingleMuon/Run2016G-PromptReco-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1']]

samples['SingleMu-Run2016B-23Sep2016-v1'] = ['/SingleMuon/Run2016B-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016B-23Sep2016-v3'] = ['/SingleMuon/Run2016B-23Sep2016-v3/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016C-23Sep2016-v1'] = ['/SingleMuon/Run2016C-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016D-23Sep2016-v1'] = ['/SingleMuon/Run2016D-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016E-23Sep2016-v1'] = ['/SingleMuon/Run2016E-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016F-23Sep2016-v1'] = ['/SingleMuon/Run2016F-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016G-23Sep2016-v1'] = ['/SingleMuon/Run2016G-23Sep2016-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_2016SeptRepro_v4']]  
samples['SingleMu-Run2016H-PromptReco-v1'] = ['/SingleMuon/Run2016H-PromptReco-v1/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_Prompt_ICHEP16JEC_v0']]  
samples['SingleMu-Run2016H-PromptReco-v2'] = ['/SingleMuon/Run2016H-PromptReco-v2/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_Prompt_ICHEP16JEC_v0']]  
samples['SingleMu-Run2016H-PromptReco-v3'] = ['/SingleMuon/Run2016H-PromptReco-v3/MINIAOD',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','crossSection=-1','globalTag=80X_dataRun2_Prompt_ICHEP16JEC_v0']]  
