root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"zee\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"zmm\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"gam\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"wen\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"wmn\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"topmu\",false,false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"topel\",false,false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"mpruned\",\"m_{pruned}[GeV]\",\"SR\",false,false\)

root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"zee\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"zmm\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"gam\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"wen\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"wmn\",false,false\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"topmu\",false,false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"topel\",false,false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"tau2tau1\",\"\#tau_{2}/\#tau_{1}\",\"SR\",false,false\)

root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"zee\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"zmm\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"gam\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"wen\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"wmn\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"topmu\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"Recoil[GeV]\",\"topel\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"met\",\"E_{T}^{miss}[GeV]\",\"SR\",false,true\)

root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"zee\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"zmm\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"gam\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"wen\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"wmn\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"topmu\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"topel\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"njet\",\"N_{jet}\",\"SR\",false,true\)

root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"zee\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"zmm\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"gam\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"wen\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"wmn\",false,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"topmu\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"topel\",false,true,true\)
root -b -q -l ../makeControlPlots.C\(\"templates_observables.root\",6,\"boostedJetPt\",\"p^{jet}_{T}[GeV]\",\"SR\",false,true\)
