### QCD samples                                                                                                                                                              
samples['ADDMonojet_d2mD5']   = ['/ADDMonoJet_MD-5_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=4.448e+00','triggerName=HLT']]
samples['ADDMonojet_d2mD6']   = ['',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=2.139e+00','triggerName=HLT']]
samples['ADDMonojet_d2mD7']   = ['/ADDMonoJet_MD-7_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.155e+00','triggerName=HLT']]
samples['ADDMonojet_d2mD8']   = ['/ADDMonoJet_MD-8_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=6.785e-01','triggerName=HLT']]
samples['ADDMonojet_d2mD9']   = ['/ADDMonoJet_MD-9_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=4.239e-01','triggerName=HLT']]
samples['ADDMonojet_d2mD10']   = ['/ADDMonoJet_MD-10_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]
samples['ADDMonojet_d2mD11']   = ['/ADDMonoJet_MD-11_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]
samples['ADDMonojet_d2mD12']   = ['/ADDMonoJet_MD-12_d-2_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]

samples['ADDMonojet_d3mD4']   = ['/ADDMonoJet_MD-4_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=4.27e+00','triggerName=HLT']]
samples['ADDMonojet_d3mD5']   = ['/ADDMonoJet_MD-5_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.427e+00','triggerName=HLT']]
samples['ADDMonojet_d3mD6']   = ['/ADDMonoJet_MD-6_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=5.749e-01','triggerName=HLT']]
samples['ADDMonojet_d3mD7']   = ['/ADDMonoJet_MD-7_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=2.664e-01','triggerName=HLT']]
samples['ADDMonojet_d3mD8']   = ['/ADDMonoJet_MD-8_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.364e-01','triggerName=HLT']]
samples['ADDMonojet_d3mD9']   = ['/ADDMonoJet_MD-9_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]
samples['ADDMonojet_d3mD10']   = ['/ADDMonoJet_MD-10_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]
samples['ADDMonojet_d3mD11']   = ['/ADDMonoJet_MD-11_d-3_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=-1','triggerName=HLT']]

samples['ADDMonojet_d4mD3']   = ['/ADDMonoJet_MD-3_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.144e+01','triggerName=HLT']]
samples['ADDMonojet_d4mD4']   = ['/ADDMonoJet_MD-4_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=2.374e+00','triggerName=HLT']]
samples['ADDMonojet_d4mD5']   = ['',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=6.528e-01','triggerName=HLT']]
samples['ADDMonojet_d4mD6']   = ['/ADDMonoJet_MD-6_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=2.213e-01','triggerName=HLT']]
samples['ADDMonojet_d4mD7']   = ['/ADDMonoJet_MD-7_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=8.817e-02','triggerName=HLT']]
samples['ADDMonojet_d4mD8']   = ['/ADDMonoJet_MD-8_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=8.817e-02','triggerName=HLT']]
samples['ADDMonojet_d4mD9']   = ['/ADDMonoJet_MD-9_d-4_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=8.817e-02','triggerName=HLT']]


samples['ADDMonojet_d5mD3']   = ['/ADDMonoJet_MD-3_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=9.234e+00','triggerName=HLT']]
samples['ADDMonojet_d5mD4']   = ['/ADDMonoJet_MD-4_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.617e+00','triggerName=HLT']]
samples['ADDMonojet_d5mD5']   = ['/ADDMonoJet_MD-5_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=3.750e-01','triggerName=HLT']]
samples['ADDMonojet_d5mD6']   = ['/ADDMonoJet_MD-6_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.076e-01','triggerName=HLT']]
samples['ADDMonojet_d5mD7']   = ['/ADDMonoJet_MD-7_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=3.668e-02','triggerName=HLT']]

samples['ADDMonojet_d6mD3']   = ['/ADDMonoJet_MD-3_d-6_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=7.821e+00','triggerName=HLT']]
samples['ADDMonojet_d6mD4']   = ['/ADDMonoJet_MD-4_d-6_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.168e+00','triggerName=HLT']]
samples['ADDMonojet_d6mD5']   = ['',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=2.288e-01','triggerName=HLT']]
samples['ADDMonojet_d6mD6']   = ['/ADDMonoJet_MD-6_d-6_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=5.571e-02','triggerName=HLT']]
samples['ADDMonojet_d6mD7']   = ['/ADDMonoJet_MD-7_d-5_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=True','addGenParticles=True','crossSection=1.693e-02','triggerName=HLT']]





