## Di-boson:                                                                                                                                                                    
samples['WWTo2L2Nu_powheg']     = ['/WWTo2L2Nu_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=True','isSignalSample=False','addGenParticles=True','crossSection=12.178','triggerName=HLT']]
samples['WWTo4Q_powheg']        = ['/WWTo4Q_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=True','isSignalSample=False','addGenParticles=True','crossSection=49.997','triggerName=HLT']]
samples['WWToLNu2Q_powheg']     = ['/WWToLNuQQ_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=True','isSignalSample=False','addGenParticles=True','crossSection=51.723','triggerName=HLT']]
samples['WWToLNu2Q_powheg_ext'] = ['/WWToLNuQQ_13TeV-powheg/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=True','isSignalSample=False','addGenParticles=True','crossSection=51.723','triggerName=HLT']]
### WZ samples
samples['WZ_pythia']       = ['/WZ_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=47.2','triggerName=HLT']]
samples['WZ_pythia_ext']   = ['/WZ_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=47.2','triggerName=HLT']]
###### ZZ samples
samples['ZZ_pythia8']      = ['/ZZ_TuneCUETP8M1_13TeV-pythia8/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=16.6','triggerName=HLT']]
