## Single-top: t-channel                                                                                                                                                                              
samples['STop_t-channel_powheg']      = ['/ST_t-channel_antitop_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=136.02','triggerName=HLT']]
samples['SATop_t-channel_powheg']     = ['/ST_t-channel_top_4f_inclusiveDecays_13TeV-powhegV2-madspin-pythia8_TuneCUETP8M1/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=80.95','triggerName=HLT']]
## Single-top: t-channel                                                                                                                                                                              
samples['STop_s-channel_amcatnlo']    = ['/ST_s-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=3.40','triggerName=HLT']]
## Single-top: tW channel                                                                                                                                                                            
samples['STop_tW-channel_powheg']     = ['/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M2T4/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=35.85','triggerName=HLT']]
samples['SAntiTop_tW-channel_powheg'] = ['/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M2T4/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=35.85','triggerName=HLT']]

## Single-top: t-channel                                                                                                                                                                              
#samples['STop_t-channel_powheg_ext']   = ['',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=44.88','triggerName=HLT']]
#samples['SATop_t-channel_powheg_ext']  = ['',['useLHEWeights=False','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=26.71','triggerName=HLT']]
## Single-top: t-channel                                                                                                                                                                              
#samples['STop_s-channel_amcatnlo_ext'] = ['',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=3.40','triggerName=HLT']]
## Single-top: tW channel                                                                                                                                                                            
#samples['STop_tW-channel_powheg_ext']     = ['/ST_tW_top_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=35.85','triggerName=HLT']]
#samples['SAntiTop_tW-channel_powheg_ext'] = ['/ST_tW_antitop_5f_inclusiveDecays_13TeV-powheg-pythia8_TuneCUETP8M1/RunIISummer16MiniAODv2-PUMoriond17_80X_mcRun2_asymptotic_2016_TrancheIV_v6_ext1-v1/MINIAODSIM',['useLHEWeights=True','addQCDPDFWeights=False','isSignalSample=False','addGenParticles=True','crossSection=35.85','triggerName=HLT']]
